export interface Company {
  id: number;
  name: string;
  category: string;
  shortDesc: string;
  desc1: string;
  desc2: string;
  desc3: string;
  desc4: string;
  img: string;
}

export const companies: Company[] = [
  {
    id: 1,
    name: "ROBOTECH ENG CO.,LTD.",
    category: "Industrial Equipment",
    shortDesc:
      "Leading Korean manufacturer of high-quality fans, blowers, and motors with 20+ years of export experience.",
    desc1: "ROBOTECH ENG CO., LTD. is a Korean engineering company specializing in industrial ventilation equipment including heavy-duty fans, blowers, and motors.",
    desc2: "Their products are widely used in factories and industrial plants requiring stable airflow and high-performance ventilation systems.",
    desc3: "ROBOTECH solutions are known for durability, energy efficiency, and strong performance in demanding environments.",
    desc4: "With years of engineering expertise, the company supports global industries through reliable ventilation technologies.",
    img: "/images/gedung.jpg",
  },
  {
    id: 2,
    name: "SENKO",
    category: "Safety Equipment",
    shortDesc:
      "Gas detectors designed for safety in hazardous environments with real-time monitoring capabilities.",
    desc1: "SENKO develops advanced gas detection technologies designed to protect workers and industrial environments.",
    desc2: "Their product portfolio includes portable gas detectors and fixed gas monitoring systems.",
    desc3: "These technologies are widely used in energy, chemical, and construction industries.",
    desc4: "SENKO focuses on safety innovation and reliable monitoring solutions for hazardous environments.",
    img: "/images/gedung.jpg",
  },
  {
    id: 3,
    name: "ANGEL TRAY",
    category: "Eco-Friendly",
    shortDesc:
      "Innovation in eco-friendly dining solutions with recyclable and biodegradable collagen trays.",
    desc1: "Angel Tray produces eco-friendly dining trays used in institutional food services.",
    desc2: "Their trays are commonly used in schools, hospitals, and cafeterias.",
    desc3: "The company emphasizes hygienic design and recyclable materials.",
    desc4: "Angel Tray promotes sustainable dining solutions and environmentally responsible manufacturing.",
    img: "/images/gedung.jpg",
  },
  {
    id: 4,
    name: "SILLIMANN Co.,Ltd.",
    category: "Lifestyle",
    shortDesc:
      "Premium silicone products from kitchenware to kidsware with award-winning design.",
    desc1: "SILLIMANN is a premium Korean lifestyle brand producing silicone kitchenware and children's tableware.",
    desc2: "Their products are made with platinum-grade silicone that is BPA-free and heat resistant.",
    desc3: "The brand combines modern design with safety and durability.",
    desc4: "SILLIMANN products are widely used by households around the world.",
    img: "/images/gedung.jpg",
  },
  {
    id: 5,
    name: "SEONGHAN CORP.",
    category: "Construction",
    shortDesc:
      "Eco-friendly waterproofing solution with excellent adhesion, flexibility, and crack-bridging.",
    desc1: "Seonghan corp. is a company, specialized in construction technology.",
    desc2: "On 2018, SeongHan Corp. is built for technical services and special overseas trading experience. As an affiliate of Smartseal, SeongHan Corp. takes charge of the exporting works for all over the world.",
    desc3: "SeongHan Corp. seeks to be admirable enterprise that pursues happiness of SeongHan partners through sharing.",
    desc4: "SeongHan Corp. also keeps pursuing positive changes for innovation and continues to challenge for the future.",
    img: "/images/seonghan.png",
  },
  {
    id: 6,
    name: "MIRICO",
    category: "Safety Tech",
    shortDesc:
      "Gas safety technology with certified detectors, alarms, and automatic shut-off systems.",
    desc1: "MIRICO develops gas safety technologies including detectors and alarm systems.",
    desc2: "Their systems help prevent accidents caused by gas leaks.",
    desc3: "Products are used in residential buildings, restaurants, and industrial facilities.",
    desc4: "MIRICO focuses on improving public safety through reliable gas monitoring technology.",
    img: "/images/gedung.jpg",
  },
  {
    id: 7,
    name: "HiMEL",
    category: "Industry",
    shortDesc:
      "HiMEL has led the seam tape industry with precision, durability, and innovation.",
    desc1: "HiMEL manufactures seam tape and industrial bonding materials.",
    desc2: "Their products are widely used in waterproof garments and textile manufacturing.",
    desc3: "The seam tape technology offers strong adhesion and durability.",
    desc4: "HiMEL continues to innovate materials for global textile industries.",
    img: "/images/gedung.jpg",
  },
  {
    id: 8,
    name: "SAVE Inc.",
    category: "Eco-Friendly",
    shortDesc:
      "SoilTopia™ is an eco-friendly soil improvement solution powered by beneficial microorganisms.",
    desc1: "SAVE Inc. develops eco-friendly agricultural technologies.",
    desc2: "Their solutions focus on soil improvement and sustainable farming.",
    desc3: "The flagship product SoilTopia™ uses beneficial microorganisms.",
    desc4: "SAVE helps farmers increase productivity while protecting the environment.",
    img: "/images/gedung.jpg",
  },
  {
    id: 9,
    name: "SAMYOUNG PLANT CO., LTD.",
    category: "Crushing",
    shortDesc:
      "Korea's leading mobile cone crusher engineered for high-capacity crushing.",
    desc1: "Samyoung Plant manufactures crushing and screening equipment for mining and construction industries.",
    desc2: "Their machines process raw materials such as stone and minerals efficiently.",
    desc3: "The equipment is designed for high capacity and heavy-duty operation.",
    desc4: "Samyoung supports infrastructure projects worldwide.",
    img: "/images/gedung.jpg",
  },
  {
    id: 10,
    name: "YKNTEC Co.,Ltd",
    category: "Eco-Friendly",
    shortDesc:
      "Offers precise all-in-one weather monitoring solutions with integrated sensors and data logging.",
    desc1: "YKNTEC develops advanced weather monitoring systems.",
    desc2: "Their devices measure environmental data such as temperature, humidity, and wind speed.",
    desc3: "The systems are used in research institutions and environmental monitoring programs.",
    desc4: "YKNTEC supports climate observation and environmental analysis.",
    img: "/images/gedung.jpg",
  },
  {
    id: 11,
    name: "FINI CO.LTD",
    category: "Eco-Friendly",
    shortDesc:
      "FINI delivers expertly designed fitness and therapy tools that enhance mobility, posture, and recovery.",
    desc1: "FINI develops fitness and rehabilitation equipment designed to improve mobility and posture.",
    desc2: "Their products support therapy, exercise, and daily wellness routines.",
    desc3: "The company focuses on simple and effective solutions for healthy lifestyles.",
    desc4: "FINI equipment is used by both professionals and home users.",
    img: "/images/gedung.jpg",
  },
  {
    id: 12,
    name: "YJBN Co.,Ltd.",
    category: "Eco-Friendly",
    shortDesc:
      "YJBN blends advanced research with natural ingredients to create high-quality haircare beauty and wellness products.",
    desc1: "YJBN produces haircare and beauty products based on natural ingredients.",
    desc2: "Their research combines cosmetic science with sustainable materials.",
    desc3: "The company also provides OEM and ODM manufacturing services.",
    desc4: "YJBN products are distributed in international beauty markets.",
    img: "/images/gedung.jpg",
  },
  {
    id: 13,
    name: "ANGEL TRAY",
    category: "Eco-Friendly",
    shortDesc:
      "Angel Tray leads innovation in eco-friendly dining solutions with recyclable Angel Ring trays and biodegradable collagen trays.",
    desc1: "Angel Tray develops environmentally friendly food trays.",
    desc2: "Their products use biodegradable materials including collagen trays.",
    desc3: "The trays help reduce plastic waste in food service industries.",
    desc4: "Angel Tray promotes sustainable dining environments.",
    img: "/images/gedung.jpg",
  },
  {
    id: 14,
    name: "Blitzen",
    category: "Eco-Friendly",
    shortDesc:
      "Blitzen redefines commercial dishwashing with patented technology, superior performance, and smart convenience.",
    desc1: "Blitzen develops commercial dishwashing machines for professional kitchens.",
    desc2: "Their technology improves cleaning efficiency and hygiene.",
    desc3: "The systems are used in restaurants, hotels, and catering services.",
    desc4: "Blitzen focuses on innovation and reliability in kitchen equipment.",
    img: "/images/gedung.jpg",
  },
  {
    id: 15,
    name: "ChemTech Solution",
    category: "Eco-Friendly",
    shortDesc:
      "ChemTech Solution has specialized in high-performance carrier tapes, cover tapes, and conductive films for semiconductor packaging.",
    desc1: "ChemTech Solution produces carrier tapes and conductive films.",
    desc2: "Their products are used in semiconductor packaging industries.",
    desc3: "The company focuses on precision manufacturing technology.",
    desc4: "ChemTech supplies electronic component manufacturers worldwide.",
    img: "/images/gedung.jpg",
  },
  {
    id: 16,
    name: "KOHER",
    category: "Eco-Friendly",
    shortDesc:
      "KOHER specializes in high-performance PCD and CBN cutting tools for the automotive, aerospace, electronics, and metal industries.",
    desc1: "KOHER manufactures high-performance cutting tools used in automotive and aerospace industries.",
    desc2: "Their precision tools improve machining accuracy and durability.",
    desc3: "The company develops advanced tool technologies for modern manufacturing.",
    desc4: "KOHER products are trusted by industrial manufacturers worldwide.",
    img: "/images/gedung.jpg",
  },
  {
    id: 17,
    name: "PC&C",
    category: "Eco-Friendly",
    shortDesc:
      "Global TOAPING offers engaging Korean language education by level, combining textbooks, online workbooks, and webtoon-style content.",
    desc1: "PC&C develops Korean language learning platforms and educational programs.",
    desc2: "Their system combines textbooks, multimedia, and digital learning content.",
    desc3: "Interactive learning tools help students learn Korean more effectively.",
    desc4: "PC&C provides education solutions for international students.",
    img: "/images/gedung.jpg",
  },
  {
    id: 18,
    name: "T-Motion Korea CO.,LTD.",
    category: "Eco-Friendly",
    shortDesc:
      "T-Motion offers premium electric and fixed grooming tables designed for comfort, safety, and hygiene.",
    desc1: "T-Motion manufactures professional grooming tables for pet care.",
    desc2: "Their products are designed for safety, hygiene, and comfort.",
    desc3: "Electric grooming tables improve efficiency for professional groomers.",
    desc4: "T-Motion products are widely used in pet salons worldwide.",
    img: "/images/gedung.jpg",
  },
  {
    id: 19,
    name: "INNOTECO",
    category: "Safety Technology",
    shortDesc:
      "From advanced sensors to smart monitoring systems, INNOTECO develops next-generation gas safety solutions that protect lives.",
    desc1: "INNOTECO develops gas safety sensors and monitoring systems.",
    desc2: "Their technology protects industrial facilities and workers.",
    desc3: "Products include advanced gas detection devices.",
    desc4: "INNOTECO supports safer working environments.",
    img: "/images/gedung.jpg",
  },
  {
    id: 20,
    name: "URBAN SOLUTION",
    category: "Eco-Friendly Technology",
    shortDesc:
      "EcoCoolRoof® is an eco-friendly roofing system with hybrid waterproofing and heat-reflective technology.",
    desc1: "EcoCoolRoof® System, a globally recognized hybrid-type cool roof waterproofing System that has acquired ENERGY STAR Certification.",
    desc2: "An international energy-saving program operated by the U.S. Federal Government.",
    desc3: "CRRC Cool Roof Certification and UL Certification (Class A), an international performance certification in the fire safety field.",
    desc4: "Designated as a green technology by Korea's Ministry of Land, Infrastructure and Transport.",
    img: "/images/urban.png",
  },
  {
    id: 21,
    name: "DAEJIN SANUP CO",
    category: "Industrial Safety",
    shortDesc:
      "DAEJIN SANUP offers flexible sprinkler drops, sprinklers, expansion joints, and gas hoses for fire protection systems.",
    desc1: "Founded in 1989, Daejin Sanup Co. has over three decades of expertise in the fire protection industry.",
    desc2: "We specialize in supplying high-quality flexible sprinkler drops, sprinkler heads, and related components.",
    desc3: "Driven by a vision to strengthen our capabilities and lead the global market.",
    desc4: "With a legacy built on integrity, innovation, and reliability.",
    img: "/images/gedung.jpg",
  },
  {
    id: 22,
    name: "RITS-N",
    category: "Animal Nutrition",
    shortDesc:
      "RITS-N develops innovative technologies in animal nutrition and health with safe, effective, and eco-friendly feed solutions.",
    desc1: "RITS-N is acronym for Radio Information Technology System-Network.",
    desc2: "Since 1995, we have been manufacturing and leading the access control system.",
    desc3: "Started with overhead door remote control system in 1996.",
    desc4: "Over years of innovation, development, and commitment to 'High Quality', 'Cost Efficient', and 'Eco-Friendly'.",
    img: "/images/rits-n.png",
  },
  {
    id: 23,
    name: "TECHNOBIO Co., Ltd.",
    category: "Eco Fuel Technology",
    shortDesc:
      "TECHNOBIO specializes in eco-friendly fuel additives for ships, boilers, and vehicles.",
    desc1: "TECHNOBIO develops eco-friendly fuel additives.",
    desc2: "Their solutions improve fuel efficiency.",
    desc3: "Products reduce emissions.",
    desc4: "The company supports sustainable energy use.",
    img: "/images/gedung.jpg",
  },
  {
    id: 24,
    name: "MEDIAIPLUS",
    category: "Healthcare Technology",
    shortDesc:
      "MEDIAIPLUS is a data-driven CRO matching platform that helps pharmaceutical and biotech companies find partners for clinical trials.",
    desc1: "MEDIAIPLUS provides clinical research matching platforms.",
    desc2: "The platform connects pharma companies with CRO partners.",
    desc3: "It accelerates clinical trial preparation.",
    desc4: "MEDIAIPLUS improves research collaboration.",
    img: "/images/gedung.jpg",
  },
  {
    id: 25,
    name: "DXG Ltd",
    category: "Industrial Monitoring",
    shortDesc:
      "DXG provides flue gas analyzers and monitoring solutions for power plants, incinerators, and petrochemical complexes.",
    desc1: "DXG develops industrial gas analyzers.",
    desc2: "Their systems monitor emissions.",
    desc3: "The equipment is used in power plants.",
    desc4: "DXG improves environmental monitoring.",
    img: "/images/gedung.jpg",
  },
  {
    id: 26,
    name: "JEIL MACHINERY",
    category: "Industrial Equipment",
    shortDesc:
      "JEIL MACHINERY delivers innovative water pump solutions with durable submersible motor pumps.",
    desc1: "JEIL manufactures water pump systems.",
    desc2: "Their pumps support agriculture and industry.",
    desc3: "Products include submersible motor pumps.",
    desc4: "JEIL provides reliable water management solutions.",
    img: "/images/gedung.jpg",
  },
  {
    id: 27,
    name: "PASCOM Co., Ltd.",
    category: "Audio Technology",
    shortDesc:
      "PASCOM is a global supplier of PA systems, amplifiers, and speakers delivering reliable and innovative audio solutions.",
    desc1: "PASCOM develops professional audio systems.",
    desc2: "Products include amplifiers and speakers.",
    desc3: "Their technology supports public address systems.",
    desc4: "PASCOM provides reliable audio solutions.",
    img: "/images/gedung.jpg",
  },
  {
    id: 28,
    name: "TWO K International",
    category: "Beauty Products",
    shortDesc:
      "TWO K International offers practical nail care solutions including One Step Gel Nail Polish and Gel Nail Strips.",
    desc1: "TWO K International develops nail beauty products.",
    desc2: "Products include gel nail strips and spray polish.",
    desc3: "They enable salon-quality results at home.",
    desc4: "The company focuses on convenient beauty technology.",
    img: "/images/gedung.jpg",
  },
  {
    id: 29,
    name: "GLOBEPOINT",
    category: "Education Technology",
    shortDesc:
      "GLOBEPOINT provides digital education solutions through VRWARE Edu School and METAWARE Edu School.",
    desc1: "GLOBEPOINT develops metaverse education platforms.",
    desc2: "Their solutions create virtual learning environments.",
    desc3: "Students can collaborate in digital classrooms.",
    desc4: "The company supports modern digital education.",
    img: "/images/gedung.jpg",
  },
  {
    id: 30,
    name: "NOVAMEDINTL Co",
    category: "Medical Beauty",
    shortDesc:
      "NOVAMEDINTL offers advanced MESO-COSMETICS solutions powered by drug delivery and exosome technology.",
    desc1: "NOVAMEDINTL develops meso-cosmetic skin treatments.",
    desc2: "Their technology uses exosome-based skincare.",
    desc3: "Products improve skin regeneration.",
    desc4: "The company focuses on advanced aesthetic solutions.",
    img: "/images/gedung.jpg",
  },
  {
    id: 31,
    name: "AriBio Co.,Ltd",
    category: "Health Technology",
    shortDesc:
      "AriBio develops brain wellness devices using vibroacoustic technology. HERZION supports cognitive health.",
    desc1: "AriBio develops vibroacoustic brain wellness devices.",
    desc2: "Their technology improves cognitive health.",
    desc3: "Devices reduce stress and enhance concentration.",
    desc4: "AriBio focuses on neurological wellness solutions.",
    img: "/images/gedung.jpg",
  },
  {
    id: 32,
    name: "CHAMSIN Holdings Co.",
    category: "Animal Nutrition",
    shortDesc:
      "Chamsin specializes in livestock feed vitamins and nutrition supplements.",
    desc1: "Chamsin produces livestock nutrition supplements.",
    desc2: "Their vitamins improve animal growth.",
    desc3: "Products support farming productivity.",
    desc4: "Chamsin supports modern livestock management.",
    img: "/images/gedung.jpg",
  },
  {
    id: 33,
    name: "DOF LTD",
    category: "Agriculture",
    shortDesc:
      "DOF leads the functional specialty fertilizer market focusing on bio-stimulants.",
    desc1: "DOF develops specialty fertilizers.",
    desc2: "Their products include bio-stimulants.",
    desc3: "These solutions improve crop productivity.",
    desc4: "DOF supports sustainable agriculture.",
    img: "/images/gedung.jpg",
  },
  {
    id: 34,
    name: "AGROBIZ Co., Ltd.",
    category: "Agriculture Technology",
    shortDesc:
      "Agrobiz provides solutions that enhance crop quality and increase agricultural productivity.",
    desc1: "Agrobiz provides agricultural technology solutions.",
    desc2: "Their products improve crop quality.",
    desc3: "Technology supports efficient farming.",
    desc4: "Agrobiz promotes modern agriculture.",
    img: "/images/gedung.jpg",
  },
  {
    id: 35,
    name: "FDFIVE Co., Ltd.",
    category: "Eco Agriculture",
    shortDesc:
      "FDFIVE develops organic fertilizers, biopesticides, and eco-friendly farming solutions.",
    desc1: "FDFIVE develops eco-friendly fertilizers.",
    desc2: "Their products support organic farming.",
    desc3: "Solutions improve soil fertility.",
    desc4: "FDFIVE promotes sustainable agriculture.",
    img: "/images/gedung.jpg",
  },
  {
    id: 36,
    name: "YESUNG F&B Co., Ltd.",
    category: "Food Innovation",
    shortDesc:
      "YESUNG F&B develops innovative vitamin-enriched cotton candy combining unique appearance and delicious taste.",
    desc1: "YESUNG develops vitamin-enriched cotton candy.",
    desc2: "Products combine nutrition and fun.",
    desc3: "The brand focuses on unique food innovation.",
    desc4: "YESUNG products target global snack markets.",
    img: "/images/gedung.jpg",
  },
  {
    id: 37,
    name: "JYFnB",
    category: "Food Products",
    shortDesc:
      "JYFnB produces high-quality Korean roasted seaweed using carefully selected ingredients and healthy perilla oil.",
    desc1: "JYFnB produces Korean roasted seaweed.",
    desc2: "Products use high-quality ingredients.",
    desc3: "Healthy oils improve flavor and nutrition.",
    desc4: "JYFnB supports modern healthy diets.",
    img: "/images/gedung.jpg",
  },
  {
    id: 38,
    name: "FORMiS",
    category: "Construction Technology",
    shortDesc:
      "FORMiS provides lightweight aluminum formwork systems designed for rapid housing construction.",
    desc1: "FORMiS Co., Ltd. can provide you the best solution with our total service system covering design, production, fabrication, packing, delivery, installation, and maintenance.",
    desc2: "Our on-going or previous projects and products can be good references for our accumulated reputation.",
    desc3: "We apply the best available technology when we make our products based on our philosophy.",
    desc4: "You can rely on our professionalism in both knowledge and experience.",
    img: "/images/formis.png",
  },
  {
    id: 39,
    name: "G&M TECH Inc.",
    category: "Industrial Pumps",
    shortDesc:
      "G&M Tech develops oil-less piston and diaphragm pumps used in medical, industrial, and smart technology applications.",
    desc1: "G&M TECH develops oil-less pumps.",
    desc2: "Their pumps are used in medical equipment.",
    desc3: "Products are also used in industrial systems.",
    desc4: "G&M TECH focuses on reliable pump technologies.",
    img: "/images/gedung.jpg",
  },
  {
    id: 40,
    name: "AIRVISION Co.,Ltd.",
    category: "Air Purification",
    shortDesc:
      "Virus Keeper filters eliminate 99.9% of dust, harmful gases, bacteria, and viruses.",
    desc1: "AIRVISION develops advanced air filtration systems.",
    desc2: "Their filters remove dust, bacteria, and viruses.",
    desc3: "Products improve indoor air quality.",
    desc4: "AIRVISION supports healthier living environments.",
    img: "/images/gedung.jpg",
  },
  {
    id: 41,
    name: "SILLIMANN Co.,Ltd.",
    category: "Lifestyle Products",
    shortDesc:
      "Sillimann produces premium silicone kitchenware, kidsware, and appliances designed with eco-friendly manufacturing.",
    desc1: "SILLIMANN produces silicone kitchenware and lifestyle products.",
    desc2: "Their products are safe and eco-friendly.",
    desc3: "Modern design improves everyday kitchen experiences.",
    desc4: "The brand is popular in global markets.",
    img: "/images/gedung.jpg",
  },
  {
    id: 42,
    name: "MIRICO",
    category: "Gas Safety Technology",
    shortDesc:
      "MIRICO provides certified gas detectors, alarms, and automatic shut-off systems.",
    desc1: "MIRICO produces gas safety monitoring devices.",
    desc2: "Their detectors identify hazardous gas leaks.",
    desc3: "Products are used in homes and industries.",
    desc4: "MIRICO improves gas safety worldwide.",
    img: "/images/gedung.jpg",
  },
  {
    id: 43,
    name: "GLO-LEE VINCI CORP",
    category: "Packaging Equipment",
    shortDesc:
      "Glo-Lee Vinci designs stainless-steel hand wrapping machines for food and fresh product packaging.",
    desc1: "GLO-LEE VINCI develops packaging equipment.",
    desc2: "Machines wrap food products efficiently.",
    desc3: "Temperature control improves packaging quality.",
    desc4: "The company supports food processing industries.",
    img: "/images/gedung.jpg",
  },
  {
    id: 44,
    name: "EG TEC",
    category: "Water Technology",
    shortDesc:
      "EG TEC develops advanced water purification and hydrogen water systems.",
    desc1: "EG TEC develops water purification systems.",
    desc2: "Their technology produces hydrogen-rich water.",
    desc3: "Products support healthy lifestyles.",
    desc4: "EG TEC focuses on clean water innovation.",
    img: "/images/gedung.jpg",
  },
  {
    id: 45,
    name: "KOSAPLUS CO.,LTD.",
    category: "Industrial Automation",
    shortDesc:
      "KOSA PLUS develops high-performance pneumatic actuators designed for reliable industrial automation.",
    desc1: "KOSAPLUS develops pneumatic actuators.",
    desc2: "Products support industrial automation systems.",
    desc3: "The equipment improves mechanical performance.",
    desc4: "KOSAPLUS focuses on reliable industrial components.",
    img: "/images/gedung.jpg",
  },
  {
    id: 46,
    name: "S-LAND Co., Ltd.",
    category: "Textile Technology",
    shortDesc:
      "S-LAND produces eco-friendly digital textile printing inks including sublimation and reactive dyes.",
    desc1: "S-LAND develops digital textile printing inks.",
    desc2: "Products include sublimation and reactive dyes.",
    desc3: "Their inks produce vibrant colors.",
    desc4: "S-LAND supports textile manufacturing industries.",
    img: "/images/gedung.jpg",
  },
  {
    id: 47,
    name: "SENTECH ENG Co., Ltd.",
    category: "Industrial Sensors",
    shortDesc:
      "SENTECH ENG manufactures industrial sensor solutions including temperature, pressure, level, and flow measurement systems.",
    desc1: "SENTECH ENG develops industrial sensors.",
    desc2: "Products measure temperature, pressure, and flow.",
    desc3: "Their sensors support industrial automation.",
    desc4: "SENTECH provides reliable measurement technologies.",
    img: "/images/gedung.jpg",
  },
];

export function getCompanyById(id: number): Company | undefined {
  return companies.find((c) => c.id === id);
}
